create database dbTransaction


CREATE TABLE CreditCardTransaction (creditCardTransactionId bigint identity not null, amountAdjustment numeric(19,2), applyITF BIT, authorizationDescription nvarchar(255), authorizationFullName nvarchar(255), authorizationStoreCode nvarchar(255), authorizationType nvarchar(255), authorizationUsername nvarchar(255),  beneficiaryIdentityDocumentNumber nvarchar(255), beneficiaryIdentityDocumentType nvarchar(255), changeFlag BIT, creditCardNumber nvarchar(255), creditCardType nvarchar(255), email nvarchar(255), statusPrint bit NULL , statusEmail bit NULL,executerIdentityDocumentNumber nvarchar(255), executerIdentityDocumentType nvarchar(255), operationCode nvarchar(255), operationDate datetime2, originalCreditCardTransactionId bigint, processTraceId binary(255), receiptType nvarchar(255), remitterFullName nvarchar(255), remitterIdentityDocumentNumber nvarchar(255), remitterIdentityDocumentType nvarchar(255), rfFullName nvarchar(255), rfStoreCode nvarchar(255), rfUserName nvarchar(255), status nvarchar(255), totalAmount numeric(19,2), transactionType nvarchar(255),executorFirstName NVARCHAR(300) ,executorSecondName NVARCHAR(300) ,executorFirstSurname NVARCHAR(300),executorSecondSurname NVARCHAR(300),beneficiaryFirstName NVARCHAR(300),beneficiarySecondName NVARCHAR(300),beneficiaryFirstSurname NVARCHAR(300),beneficiarySecondSurname NVARCHAR(300) ,remitterFirstName NVARCHAR(300) ,remitterSecondName NVARCHAR(300),remitterFirstSurname NVARCHAR(300)  ,internalOperationCode NVARCHAR(300),remitterSecondSurname NVARCHAR(300),  primary key (creditCardTransactionId))
CREATE TABLE PaymentDetail(	paymentDetailId bigint IDENTITY(1,1) NOT NULL,amount decimal(19, 2) NULL,	pendingPayDollarsTotalAmount decimal(19, 2) NULL,	pendingPaySolesTotalAmount decimal(19, 2) NULL,	currency nvarchar(255) NULL,	paymentMethodType nvarchar(255) NULL,	creditCardTransactionId bigint NOT NULL,	amountReceive decimal(19, 2) NULL, status  nvarchar(100), billingType nvarchar(300), PRIMARY KEY (paymentDetailId))
CREATE TABLE Parameter(id bigint  NULL, code varchar(50) NULL,	createdBy varchar(50) NULL,	createdDate datetime2(7) NULL,	lastModifiedBy varchar(50) NULL,	lastModifiedDate datetime2(7) NULL,	version int NULL,	description varchar(255) NULL,	name varchar(150) NULL,	status int NULL,	parameterTypeId bigint NOT NULL,	symbol varchar(100) NULL, 	bankCode varchar(100) NULL,	maxCurrency varchar(100) NULL,	validation nvarchar(50))

alter table PaymentDetail add constraint FKxnn7i1nyfye70n2dbkhdqxo2 foreign key (creditCardTransactionId) references CreditCardTransaction

